"""Initial Migration 2

Revision ID: 31db0122b277
Revises: f61a8253fffe
Create Date: 2020-01-09 23:55:56.388575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31db0122b277'
down_revision = 'f61a8253fffe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
